name: Snake Oluştur

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün otomatik günceller
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        with:
          github_user_name: mchtx  # BURAYA KENDİ KULLANICI ADINI YAZ
          svg_output_path: ./snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          branch: main
          message: "Yılan güncellendi"
